version: "2"
services:
  centos6:
    build:
      dockerfile: Dockerfile.centos6
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /root/rpmbuild/RPMS/x86_64/nginx-${NGINX_VERSION}-1.el6.ngx.x86_64.rpm /tmp
    volumes:
      - .:/tmp:rw

  centos7:
    build:
      dockerfile: Dockerfile.centos7
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /root/rpmbuild/RPMS/x86_64/nginx-${NGINX_VERSION}-1.el7.ngx.x86_64.rpm /tmp
    volumes:
      - .:/tmp:rw

  ubuntu1604:
    build:
      dockerfile: Dockerfile.ubuntu1604
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /usr/local/src/nginx_${NGINX_VERSION}-1~xenial_amd64.deb /tmp
    volumes:
      - .:/tmp:rw

  ubuntu1804:
    build:
      dockerfile: Dockerfile.ubuntu1804
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /usr/local/src/nginx_${NGINX_VERSION}-1~bionic_amd64.deb /tmp
    volumes:
      - .:/tmp:rw

  debian9:
    build:
      dockerfile: Dockerfile.debian9
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /usr/local/src/nginx_${NGINX_VERSION}-1~stretch_amd64.deb /tmp
    volumes:
      - .:/tmp:rw

  debian10:
    build:
      dockerfile: Dockerfile.debian10
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGX_MRUBY_VERSION: ${NGX_MRUBY_VERSION}
    command: cp -a /usr/local/src/nginx_${NGINX_VERSION}-1~buster_amd64.deb /tmp
    volumes:
      - .:/tmp:rw
